WorkAndTravelUSA/WorkAndTravelUSA/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WorkAndTravelUSA.Models
{
    public class Location
    {
        public Location () { }
        [Key]
        public int Id { get; set; }
        [Required]
        public int IdClient { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [Display(Name = "Image")]

        public string imgUrl { get; set; }

        public int Raiting { get; set; }
        public int NumOfRatings { get; set; }
        public int finalRating { get; set; }
        public virtual List<Comment> Comments { get; set;}

    }
}

WorkAndTravelUSA/WorkAndTravelUSA/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorkAndTravelUSA.Models;

namespace WorkAndTravelUSA.Controllers
{
    [Authorize]
    public class LocationsController : Controller
    {
        private UsaContext db = new UsaContext();

        // GET: Locations
        [AllowAnonymous]
        public ActionResult Index()
        {
          
            return View(db.locationModels.ToList());
        }

        //Get: Locations/CreateComment
        public ActionResult CreateComment(int id)
        {
            var model = new Comment();

            var q = db.clientModels.Single(u => u.oduser == User.Identity.Name);
            model.idClient = q.Id;

            model.IdLoc = id;
            return RedirectToAction("Create", "Comments", model);
        }
        // GET: Locations/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.locationModels.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdClient,Name,State,Description,imgUrl")] Location location)
        {
            if (ModelState.IsValid)
            {
                location.IdClient = db.clientModels.Single(u => u.oduser == User.Identity.Name).Id;
                db.locationModels.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.locationModels.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdClient,Name,State,Description,imgUrl")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }
        public JsonResult GetAllUser()
        {
            List<Client> clients = new List<Client>();

            string canVote = "No";
            clients = db.clientModels.ToList();
            foreach (Client c in clients)
            {
                if (c.oduser == User.Identity.Name && c.hasVote == "No")
                {
                    canVote = "Yes";
                    c.hasVote = "Yes";

                    db.SaveChanges();
                    break;
                }

            }

            return new JsonResult { Data = canVote, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public JsonResult SaveLocationRating(Location location)
        {
            
            if (db.locationModels.Find(location.Id).NumOfRatings != 0)
            {
                db.locationModels.Find(location.Id).Raiting = db.locationModels.Find(location.Id).Raiting + location.Raiting;
                db.locationModels.Find(location.Id).NumOfRatings = db.locationModels.Find(location.Id).NumOfRatings + 1;
                db.SaveChanges();

                db.locationModels.Find(location.Id).finalRating = db.locationModels.Find(location.Id).Raiting / db.locationModels.Find(location.Id).NumOfRatings;
                

            }
            else
            {
                db.locationModels.Find(location.Id).Raiting = location.Raiting;
                db.locationModels.Find(location.Id).finalRating = location.Raiting;
                db.locationModels.Find(location.Id).NumOfRatings = 1;
            }


            db.SaveChanges();

            return Json(location);
        }
        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.locationModels.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.locationModels.Find(id);
            db.locationModels.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WorkAndTravelUSA/WorkAndTravelUSA/Views/Locations/Create.cshtml
@model WorkAndTravelUSA.Models.Location

@{
    ViewBag.Title = "Create";
}

<div class="container">

    <h2 class="text-center py-4">Креирај локација</h2>
    <div class="row m-auto py-4" style="width:20em; padding: inherit;">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal" style="width:20em;">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.imgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.imgUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.imgUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group ">
                    <div class="col-md-offset-2 col-md-10 text-center col-6">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                    
                </div>
            </div>
        }

            <div class="row text-center justify-content-center w-100">
                @Html.ActionLink("Back to List", "Index")
            </div>
    </div>
</div>

WorkAndTravelUSA/WorkAndTravelUSA/Views/Locations/Delete.cshtml
@model WorkAndTravelUSA.Models.Location

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdClient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdClient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imgUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imgUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WorkAndTravelUSA/WorkAndTravelUSA/Views/Locations/Details.cshtml
@model WorkAndTravelUSA.Models.Location

@{
    ViewBag.Title = "Details";
    var db = new WorkAndTravelUSA.Models.UsaContext();
    var cl1 = db.clientModels.Find(Model.IdClient).Name;
}

<div class="container">

    <h2 class="text-center text-danger py-4">Details Location</h2>

    <div>
        <hr />
        <dl class="dl-horizontal row">
            <div class="col-6 m-auto text-center">

                <dt>
                    Name of creator
                </dt>

                <dd>
                    @cl1
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.State)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.State)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

            </div>

            <div class="col-6 m-auto">

                <dd>
                    <img src="@Model.imgUrl" style="width:30em; height:20em" />
                </dd>

            </div>

        </dl>


    </div>
    <div class="text-center"    >
        Raiting: <br />
        <span class="text-warning">
            <i class="ratingStar far fa-star" data-value="1"></i>
            <i class="ratingStar far fa-star" data-value="2"></i>
            <i class="ratingStar far fa-star" data-value="3"></i>
            <i class="ratingStar far fa-star" data-value="4"></i>
            <i class="ratingStar far fa-star" data-value="5"></i>
        </span>
        Average rating: @Model.finalRating
        <input type="hidden" name="Rating" id="ratingsValue" />
        <p>
            @if (User.IsInRole("Administrator"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id })}
            @Html.ActionLink("Back to List", "Index") |
            @Html.ActionLink("Add comment", "CreateComment", new { id = Model.Id })
            @if (User.IsInRole("Administrator"))
            {
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
            }



        </p>

       
        Comments:
        <ul style="list-style-type:none;">
            @foreach (WorkAndTravelUSA.Models.Comment comment in Model.Comments)
            {
                <li>
                    @{
                        var cl = db.clientModels.Find(comment.idClient).Name;
                    }
                    <div class="bg-light">
                        <p> <span class="text-danger">@cl</span> : @comment.Description</p>
                    </div>
                </li>
            }
        </ul>

    </div>

</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".ratingStar").hover(function () {
            $(".ratingStar").addClass("far").removeClass("fas");

            $(this).addClass("fas").removeClass("far");
            $(this).prevAll(".ratingStar").addClass("fas").removeClass("far");
        });
    });
    $(".ratingStar").click(function () {
        var starValue = $(this).attr("data-value");
        $("#ratingsValue").val(starValue);

        //here I start
                        $.ajax({
                            url: "@Url.Action("GetAllUser","Locations")",
                            data: "",
                            type: "GET",
                            dataType: "json",
                            success: function (data) {
                                console.log(data);
                                if (data == "Yes") {
                                    var jsonData = {
                                        Id: @Model.Id,
                                        Raiting: starValue
                                    };


                                    $.ajax({
                                        type: "POST",
                                        url: '@Url.Action("SaveLocationRating", "Locations")',
                                        contentType: "application/json;charset=utf-8",
                                        data: JSON.stringify(jsonData),
                                        dataType: "json",
                                        success: function () {
                                            console.log("success");
                                        }
                                    });
                                }
                                else {
                                    alert("You have already voted!")
                                }
                                
                            },
                            error: function () {
                                alert("You must be logged in");
                            }
                        });
        //here I end

        
 });
</script>

WorkAndTravelUSA/WorkAndTravelUSA/Views/Locations/Edit.cshtml
@model WorkAndTravelUSA.Models.Location

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Location</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdClient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdClient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdClient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WorkAndTravelUSA/WorkAndTravelUSA/Views/Locations/Index.cshtml
@model IEnumerable<WorkAndTravelUSA.Models.Location>

@{
    ViewBag.Title = "Index";
}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img src="~/Images/cover.jpg" class="d-block w-100" style="height:30em" alt="cover">
        </div>
        <div class="carousel-item">
            <img src="~/Images/WORK-TRAVEL-USA-2020-Slideshow-1000x460.png" class="d-block w-100" style="height:30em" alt="second">
        </div>
        <div class="carousel-item">
            <img src="~/Images/Work-and-Travel-USA-2018-Lifeguards-in-New-Jersey-678x381.jpg" class="d-block w-100" style="height:30em" alt="three">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="container py-4">
    <h2 class="text-center">Креирајте локација и споделете го вашето искуство</h2>
    <div class="row py-3 ">
        <button class="btn btn-light m-auto" style="text-decoration: none;">
            @Html.ActionLink("Креирај локација", "Create")
        </button>
    </div>
    <div class="row text-center">
        @foreach (var item in Model)
        {

            var db = new WorkAndTravelUSA.Models.UsaContext();
            var NameOfClient = db.clientModels.Find(item.IdClient).Name;
        <div class="col-md-4 py-2">
            <div class="card m-auto" style="width: 18rem;">
                <img src="@item.imgUrl" class="card-img-top" style="height:12em" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.State</p>
                    <button class="btn btn-light">@Html.ActionLink("Детали", "Details", new { id = item.Id })</button>
                </div>
            </div>
        </div>
        }
    </div>
</div>